### ISSUE TITLE
add a list of contributors

### ISSUE THREAD

**Issue by th-schwarz** [th-schwarz/GithubReleaseNotesCreator#1]
should be optional the end of the release notes
contributors whose username ends with [bot], such as dependabot[bot] and github-actions[bot], should be automatically excluded. 
```yaml
ghrnc:
  contributors:
    enabled: false
    title: "Contributors"
    message: "Thank you to all the contributors who worked on this release."
    excludes: ["core-developer"]
```
